[settings]
color = true
experimental = true

[tools]
node = "latest"
opencode = "latest"
rust = "1.98.1"
"aqua:helix-editor/helix" = { version = "latest" }
"aqua:openai/codex" = "latest"
"cargo:cargo-release" = "latest"
"npm:heroku" = "latest"
