[settings]
color = true
experimental = true

[tools]
node = "latest"
opencode = "latest"
rust = "latest"
"npm:defuddle" = { version = "latest", depends = ["node"] }
"aqua:openai/codex" = "latest"
"aqua:helix-editor/helix" = { version = "latest" }
